name=TouchToggle
version=0.0.2
author=Michael Schaff <schafmb@gmail.com>
maintainer=Michael Schaff <schafmb@gmail.com>
sentence=A library for the Berrett Hill Shop Touch Toggle control for model railroad turnouts.
paragraph=The library implements the protocol for interfacing the Berrett Hill Shop Touch Toggle to the Arduino platform.
category=Other
url=https://github.com/schaffmb/TouchToggle/
architectures=*
